get http://localhost:3000/products.json

###

get http://localhost:3000/products/3.json

###

post http://localhost:3000/products.json
Content-Type: application/json

{
  "name": "Abosultely Everything",
  "price": "100",
  "image_url": "https://images.heb.com/is/image/HEBGrocery/001476509?fit=constrain,1&wid=800&hei=800&fmt=jpg&qlt=85,0&resMode=sharp2&op_usm=1.75,0.3,2,0",
  "description": "Woah it looks nothing like an energy drink."
}

###

patch http://localhost:3000/products/1.json
Content-Type: application/json

{
  "supplier_id": 1
}

###

delete http://localhost:3000/products/6.json

