@hostname = api.example.com
@port = 8080
@host = {{hostname}}:{{port}}
@contentType = application/json

###

get http://localhost:3000/products.json

###

get http://localhost:3000/products/3.json

###

get http://localhost:3000/users.json

###

post http://localhost:3000/users.json
# DO NOT RUN, WILL destroy terminal
Content-Type: application/json

{
  "name": "Eric Taupier",
  "email": "erictaupier@gmail.com",
  "password": "password321",
  "password_confirmation": "password321"
}

###

post http://localhost:3000/sessions

{
  
}


###

patch http://localhost:3000/products/1.json
Content-Type: application/json

{
  "supplier_id": 1
}

###

delete http://localhost:3000/products/1.json

###

get http://localhost:3000/orders.json

###

post http://localhost:3000/orders.json
Content-Type: application/json

{
  "user_id": 1,
  "product_id": 2,
  "quantity": 1,
  "subtotal": 7,
  "tax": 1,
  "total": 8
}

###

delete http://localhost:3000/orders/2.json

###

post http://localhost:3000/carted_products.json
Content-Type: application/json

{
  "quantity": 1,
  "product_id": 1
}
